# Generated by Django 4.1 on 2022-12-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habitos", models.CharField(max_length=255)),
                ("alergias", models.CharField(max_length=255)),
                ("cirugias", models.TextField(max_length=400)),
                ("hospitalizaciones", models.CharField(max_length=255)),
                ("antecedentes_morbidos", models.CharField(max_length=255)),
                ("peso", models.FloatField()),
                ("talla", models.FloatField()),
                ("imc", models.FloatField()),
                ("frecuencia_cardiaca", models.IntegerField()),
                ("frecuencia_respiratoria", models.IntegerField()),
                ("so2", models.IntegerField()),
                ("presion_arterial", models.IntegerField()),
                ("descripcion_dolor", models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_usuario", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Sesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_sesion", models.IntegerField()),
                ("objetivo_sesion", models.TextField(max_length=400)),
                ("observacion", models.TextField(max_length=400)),
                ("evolucion", models.TextField(max_length=600)),
                ("alta_kinesiologica", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido_paterno", models.CharField(max_length=30)),
                ("apellido_materno", models.CharField(max_length=30)),
                ("rut", models.CharField(max_length=10)),
                ("mail", models.CharField(max_length=45)),
                ("telefono", models.IntegerField()),
                ("usuario", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=45)),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.rol"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("apellido_paterno", models.CharField(max_length=30)),
                ("apellido_materno", models.CharField(max_length=30)),
                ("rut", models.CharField(max_length=10)),
                ("fecha_nacimiento", models.DateField()),
                ("sexo", models.CharField(max_length=10)),
                ("telefono", models.CharField(max_length=45)),
                ("direccion", models.CharField(max_length=45)),
                ("prevision", models.CharField(max_length=45)),
                ("diagnostico_medico", models.TextField(max_length=600)),
                ("indicacion_medica", models.TextField(max_length=600)),
                ("examenes", models.TextField(max_length=600)),
                ("medicamentos", models.TextField(max_length=600)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.expediente"
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.sesion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("estado", models.IntegerField()),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.paciente"
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.personal"
                    ),
                ),
                (
                    "personal_rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.rol"
                    ),
                ),
            ],
        ),
    ]
