# Generated by Django 4.1 on 2022-12-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="examenes",
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="expediente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.expediente",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="medicamentos",
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="sesion",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.sesion"
            ),
        ),
    ]
